# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b4d71ebb3887696ff48d8228874e0b89b088567ba5632df38a692aa9454552b732c73a653a5a9a02b88c305937bb48164347f57ec6bc99b0e9733dc2ddeb41

test:
  secret_key_base: be81eb1e5aff4d4b63817c81a7c89e9a08fdeb3839d60259d44ec09bc9713c486cbb5150c6eb29361192cf73ea82c834b29bd8131f5d1be146a6f0de2bd206ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
